language: php
php:
  - 5.3

before_script:
  - cp app/config/parameters.yml.dist app/config/parameters.yml
  - wget http://getcomposer.org/composer.phar
  - php composer.phar install
  - mysql -uroot -e 'create database bikini;'
  - mysql -uroot -e 'grant all on bikini.* to bikini@localhost identified by "bikini";'
  - php app/console doctrine:schema:create
  - php app/console doctrine:fixtures:load

script: phpunit -c app/phpunit.xml

notifications:
  email:
    - paul.seiffert@mayflower.de
