_translate_home:
    pattern: /translate/
    defaults: { _controller: opensixtBikiniTranslateBundle:Translate:index }

_translate_edittext:
    pattern: /translate/edittext/{page}
    defaults: { _controller: opensixtBikiniTranslateBundle:Translate:edittext, page: 1 }
    requirements:
        page: \d+
