_translate_home:
    pattern: /translate/
    defaults: { _controller: opensixtBikiniTranslateBundle:Translate:index }

_translate_setlocale:
    pattern: /translate/setlocale/
    defaults: { _controller: opensixtBikiniTranslateBundle:Translate:setlocale }

_translate_edittext:
    pattern: /translate/edittext/{locale}/{page}
    defaults: { _controller: opensixtBikiniTranslateBundle:Translate:edittext, locale: 'empty', page: 1 }
    requirements:
        page: \d+

_translate_searchstring:
    pattern: /translate/searchstring/{page}
    defaults: { _controller: opensixtBikiniTranslateBundle:Translate:searchstring, page: 1 }
    requirements:
        page: \d+

_translate_changetext:
    pattern: /translate/changetext/{page}
    defaults: { _controller: opensixtBikiniTranslateBundle:Translate:changetext, page: 1 }
    requirements:
        page: \d+

