parameters:
#    opensixt_bikini_translate.example.class: opensixt\BikiniTranslateBundle\Example

services:
#    opensixt_bikini_translate.example:
#        class: %opensixt_bikini_translate.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
