parameters:
    opensixt_searchstring.class: opensixt\BikiniTranslateBundle\Services\SearchString

services:
    opensixt_searchstring:
        class: %opensixt_searchstring.class%
        arguments: [@doctrine]
#        arguments: [@service_id, "plain_value", %parameter%]
