parameters:
    opensixt_searchstring.class: opensixt\BikiniTranslateBundle\Services\SearchString
    opensixt_edittext.class: opensixt\BikiniTranslateBundle\Services\EditText
    opensixt_flaggedtext.class: opensixt\BikiniTranslateBundle\Services\FlaggedText
    opensixt_copydomain.class: opensixt\BikiniTranslateBundle\Services\CopyDomain

services:
    opensixt_searchstring:
        class: %opensixt_searchstring.class%
        arguments: [@doctrine]
#        arguments: [@service_id, "plain_value", %parameter%]

    opensixt_edittext:
        class: %opensixt_edittext.class%
        arguments: [@doctrine, %common_language%, %text_revision_control%]

    opensixt_flaggedtext:
        class: %opensixt_flaggedtext.class%
        arguments: [@doctrine]

    opensixt_copydomain:
        class: %opensixt_copydomain.class%
        arguments: [@doctrine, %common_language%, %text_revision_control%]
