opensixtUserAdminBundle:
    resource: "@opensixtUserAdminBundle/Resources/config/routing.yml"
    prefix:   /

opensixtBikiniTranslateBundle:
    resource: "@opensixtBikiniTranslateBundle/Resources/config/routing.yml"
    prefix:   /