security:
    encoders:
        opensixt\UserAdminBundle\Entity\User:
            algorithm:        md5
            encode_as_base64: false
            iterations:       1 

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        main:
            entity: { class: opensixtUserAdminBundle:User, property: username }

    firewalls:

        main:
            pattern: ^/
            form_login:
                check_path: /login_check
                login_path: /login
                default_target_path: /admin
            logout: 
                target: /admin
            security: true
            anonymous: true
     #   dev:
     #       pattern:  ^/(_(profiler|wdt)|css|images|js)/
     #       security: false

     #   login:
     #       pattern:  ^/demo/secured/login$
     #       security: false

     #   secured_area:
     #       pattern:    ^/demo/secured/
     #       form_login:
     #           check_path: /demo/secured/login_check
     #           login_path: /demo/secured/login
     #       logout:
     #           path:   /demo/secured/logout
     #           target: /demo/
            #anonymous: ~
            #http_basic:
            #    realm: "Secured Demo Area"

    access_control:
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
        #- { path: ^/_internal, roles: IS_AUTHENTICATED_ANONYMOUSLY, ip: 127.0.0.1 }
        - { path: /admin/.*, roles: ROLE_USER }
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
