parameters:
#    opensixt_content.example.class: opensixt\ContentBundle\Example

services:
#    opensixt_content.example:
#        class: %opensixt_content.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
