_user_admin_login:
    pattern:  /login
    defaults: { _controller: opensixtUserAdminBundle:Security:login }

_user_admin_check:
    pattern: /login_check

_user_admin_logout:
    pattern: /logout

_user_admin_home:
    pattern: /admin/
    defaults: { _controller: opensixtUserAdminBundle:Admin:index }

_admin_userlist:
    pattern: /admin/userlist/{page}
    defaults: { _controller: opensixtUserAdminBundle:Admin:userlist, page: 1 }
    requirements:
        page: \d+

_admin_user:
    pattern: /admin/user/{id}
    defaults: { _controller: opensixtUserAdminBundle:Admin:userdata, id: 0 }
    requirements:
        id: \d+

_admin_grouplist:
    pattern: /admin/grouplist/{page}
    defaults: { _controller: opensixtUserAdminBundle:Admin:grouplist, page: 1 }

_admin_group:
    pattern: /admin/group/{id}
    defaults: { _controller: opensixtUserAdminBundle:Admin:groupdata, id: 0 }
    requirements:
        id: \d+

_admin_langlist:
    pattern: /admin/langlist/{page}
    defaults: { _controller: opensixtUserAdminBundle:Admin:langlist, page: 1 }
    requirements:
        page: \d+

_admin_lang:
    pattern: /admin/lang/{id}
    defaults: { _controller: opensixtUserAdminBundle:Admin:langdata, id: 0 }
    requirements:
        id: \d+

_admin_reslist:
    pattern: /admin/reslist/{page}
    defaults: { _controller: opensixtUserAdminBundle:Admin:reslist, page: 1 }
    requirements:
        page: \d+

_admin_resource:
    pattern: /admin/resource/{id}
    defaults: { _controller: opensixtUserAdminBundle:Admin:resdata, id: 0 }
    requirements:
        id: \d+