parameters:
  opensixt.user_admin.controller.user.class: "opensixt\UserAdminBundle\Controller\UserController"

services:
  opensixt.user_admin.controller.user:
    class: %opensixt.user_admin.controller.user.class%
    scope: request
    properties:
      request: @request
      translator: @translator
      em: @doctrine.orm.entity_manager
      formFactory: @form.factory
      templating: @templating
      paginator: @knp_paginator
      securityContext: @security.context
      router: @router